# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1b62247c065ee501560be96ee1e69d22901ef7c1b9e6ac281c7f15f0175e152b4b84440c3522f17f03b560085240400de32ef12077cb332e0739ba77b1b0a39

test:
  secret_key_base: ef2b549d01425667ab0bb517b5ad0d07925683c753b62f899a8cb357d6e52b0b7b41229a113718d06bbfae26b1c57001f6f4f8621074f6a59faa72b4412ae005

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
